"""
ECR record type structures.

Each structure maps field positions to (name, length, type, required) tuples.
Positions are 1-based as per the ISAgri documentation.
Types: "Alpha" (left-aligned, space-padded), "Num" (right-aligned, zero-padded), "Date" (jjmmaaaa).
"""

STRUCT_VER = {
    1:  ("Type enregistrement",              6,  "Alpha", True),
    7:  ("Version ISACOMPTA minimale",        7,  "Num",   True),
    14: ("Zone obligatoire",                  4,  "Num",   True),
    18: ("Flag destruction ecritures",        1,  "Num",   False),
    19: ("Libelle du fichier",               30,  "Alpha", False),
    49: ("Type ANSI/ASCII",                   1,  "Num",   False),
}

STRUCT_DOS = {
    1:  ("Type enregistrement",              6,  "Alpha", True),
    7:  ("Numero de dossier",                8,  "Alpha", True),
    15: ("Libelle du dossier",              30,  "Alpha", True),
    45: ("Date derniere cloture",            8,  "Date",  False),
    53: ("Flag MAJ analytique",              1,  "Num",   False),
    54: ("Flag MAJ comptes",                 1,  "Num",   False),
    55: ("Flag MAJ journaux",                1,  "Num",   False),
    56: ("Flag MAJ codes TVA",               1,  "Num",   False),
    57: ("Filer",                            1,  "Num",   False),
    58: ("Filer",                            1,  "Num",   False),
    59: ("Taille des comptes du dossier",    2,  "Num",   False),
    61: ("Filer",                            1,  "Num",   False),
    62: ("Filer",                            3,  "Alpha", False),
    65: ("Flag MAJ affectations analytique", 1,  "Num",   False),
    66: ("Code etalon 1",                    7,  "Alpha", False),
    73: ("Code etalon 2",                    7,  "Alpha", False),
    80: ("Code etalon ana",                  7,  "Alpha", False),
}

STRUCT_EXO = {
    1:  ("Type enregistrement",              6,  "Alpha", True),
    7:  ("Date debut exercice",              8,  "Date",  True),
    15: ("Date fin exercice",                8,  "Date",  True),
    23: ("Flag destruction ecritures",       1,  "Num",   False),
    24: ("Filer",                            1,  "Num",   False),
    25: ("Filer",                           11,  "Num",   False),
    36: ("Devise",                           3,  "Alpha", False),
    39: ("Date declaration TVA",             8,  "Date",  False),
    47: ("Periodicite TVA",                  1,  "Num",   False),
}

STRUCT_CPT = {
    1:   ("Type enregistrement",             6,  "Alpha", True),
    7:   ("Numero de compte",               10,  "Alpha", True),
    17:  ("Libelle",                        30,  "Alpha", True),
    47:  ("Code alpha",                     10,  "Alpha", False),
    57:  ("Unite quantite 1",                3,  "Alpha", False),
    60:  ("Libelle quantite 1",             10,  "Alpha", False),
    70:  ("Unite quantite 2",                3,  "Alpha", False),
    73:  ("Libelle quantite 2",             10,  "Alpha", False),
    83:  ("Numero autorise",                 1,  "Num",   False),
    84:  ("Code lettrage",                   3,  "Alpha", False),
    87:  ("Type de compte",                  2,  "Alpha", False),
    89:  ("Tiers",                           7,  "Alpha", False),
    96:  ("Compte associe debiteur",        10,  "Alpha", False),
    106: ("Compte associe crediteur",       10,  "Alpha", False),
    116: ("Centralisation Grand Livre",      1,  "Num",   False),
    117: ("Sens de saisie privilegiee",      2,  "Alpha", False),
    119: ("Code TVA associe",                2,  "Alpha", False),
    121: ("TVA autorisee comptes 4",         1,  "Num",   False),
    122: ("Compte de regroupement",         10,  "Alpha", False),
    132: ("Filer",                          10,  "Alpha", False),
    142: ("Compte lie",                     10,  "Alpha", False),
    152: ("Lettrable",                       1,  "Num",   False),
    153: ("Detail a-nouveaux non lettres",   1,  "Num",   False),
    154: ("Pointable",                       1,  "Num",   False),
    155: ("Libelle du mouvement",           30,  "Alpha", False),
    185: ("Nombre d'activites",              4,  "Num",   False),
    189: ("Code devise du compte",           3,  "Alpha", False),
    192: ("Indicateur Gestion commerciale",  1,  "Num",   False),
    193: ("Affichage quantite 1",            1,  "Num",   False),
    194: ("Affichage quantite 2",            1,  "Num",   False),
    195: ("Arret colonne TVA",               1,  "Num",   False),
    196: ("Affectation obligatoire",         1,  "Num",   False),
    197: ("Affectation possible",            1,  "Num",   False),
    198: ("Flag devise",                     1,  "Num",   False),
    199: ("Flag presence remarque",          1,  "Num",   False),
    200: ("Flag revision",                   1,  "Num",   False),
    201: ("Flag visa",                       1,  "Num",   False),
    202: ("Cycle",                          11,  "Num",   False),
    213: ("Filer etalon",                   14,  "Alpha", False),
    227: ("Indicateur TVA encaissement",     1,  "Num",   False),
    228: ("Nombre de jours a l'echeance",    3,  "Num",   False),
    231: ("Echeance en fin de mois",         1,  "Num",   False),
    232: ("Libelle numero",                 10,  "Alpha", False),
    242: ("Libelle Date 1",                 10,  "Alpha", False),
    252: ("Libelle Date 2",                 10,  "Alpha", False),
    262: ("Categorie de compte",             1,  "Num",   False),
    263: ("Code collaborateur visa",         7,  "Alpha", False),
    270: ("Date modification visa",          8,  "Date",  False),
    278: ("Type de tiers",                   2,  "Alpha", False),
    280: ("Type de reglement par defaut",    2,  "Alpha", False),
    282: ("Type decalage delai facture",     2,  "Alpha", False),
    284: ("Mode prise en compte decalage",   2,  "Alpha", False),
    286: ("Delai apres fin decade/mois",     3,  "Alpha", False),
    289: ("Type decalage delai fin decade",  2,  "Alpha", False),
    291: ("Flag commentaire balance",        1,  "Num",   False),
}

STRUCT_ECR = {
    1:   ("Type enregistrement",             6,  "Alpha", True),
    7:   ("Code journal",                    2,  "Alpha", True),
    9:   ("Date de la piece",                8,  "Date",  True),
    17:  ("Numero de piece",                 8,  "Alpha", False),
    25:  ("Libelle de l'ecriture",          30,  "Alpha", True),
    55:  ("Filer",                           8,  "Alpha", False),
    63:  ("Code du site",                    7,  "Alpha", False),
    70:  ("Code utilisateur",                7,  "Alpha", False),
    77:  ("Code emetteur",                   3,  "Alpha", False),
    80:  ("Filer",                           2,  "Num",   False),
    82:  ("Code ecriture",                   9,  "Num",   False),
    91:  ("Filer",                           1,  "Num",   False),
    92:  ("Flag ecriture non modifiable",    1,  "Num",   False),
    93:  ("Date de creation",                8,  "Date",  False),
    101: ("Date de modification",            8,  "Date",  False),
    109: ("Filer",                          11,  "Num",   False),
    120: ("Flag destruction ecriture",       1,  "Num",   False),
    121: ("Devise",                          3,  "Alpha", False),
    124: ("Type de l'ecriture",              2,  "Alpha", False),
    126: ("Filer",                           1,  "Num",   False),
    127: ("Compte de contre partie",        10,  "Alpha", False),
    137: ("Flag presence commentaire",       1,  "Num",   False),
    138: ("Numero de modification",         11,  "Num",   False),
    149: ("Nom fichier image",              30,  "Alpha", False),
    179: ("Filler",                          3,  "Num",   False),
    182: ("Filler",                          5,  "Num",   False),
    187: ("Type de document",                2,  "Alpha", False),
    189: ("Flag export interface sortie",    1,  "Num",   False),
    190: ("Filer",                           7,  "Alpha", False),
    197: ("Filer",                          38,  "Alpha", False),
    235: ("Type de reglement",               2,  "Alpha", False),
    237: ("Registre TVA",                   10,  "Num",   False),
    247: ("Heure de modification",           9,  "Alpha", False),
    256: ("Date de validation",              8,  "Date",  False),
    264: ("Taux de change",                  8,  "Num",   False),
    272: ("Numero de facture",              15,  "Alpha", False),
    287: ("Mode de reglement",              10,  "Alpha", False),
}

STRUCT_MVT = {
    1:   ("Type enregistrement",             6,  "Alpha", True),
    7:   ("Compte",                         10,  "Alpha", True),
    17:  ("Libelle mouvement",              30,  "Alpha", False),
    47:  ("Montant debit",                  13,  "Num",   False),
    60:  ("Montant credit",                 13,  "Num",   False),
    73:  ("Quantite 1",                     11,  "Num",   False),
    84:  ("Quantite 2",                     11,  "Num",   False),
    95:  ("Numero",                          8,  "Alpha", False),
    103: ("Code TVA",                        2,  "Alpha", False),
    105: ("Code TVA associe au compte",      2,  "Alpha", False),
    107: ("Flag lettrage",                   1,  "Num",   False),
    108: ("Code lettrage",                   3,  "Alpha", False),
    111: ("Date de pointage",                8,  "Date",  False),
    119: ("Nombre d'activites",              4,  "Num",   False),
    123: ("Flag echeances",                  1,  "Num",   False),
    124: ("Date de declaration",             8,  "Date",  False),
    132: ("Code TVA 2",                      2,  "Alpha", False),
    134: ("Code TVA 3",                      2,  "Alpha", False),
    136: ("Filler",                          3,  "Num",   False),
    139: ("Filler",                          5,  "Num",   False),
    144: ("Filler",                          8,  "Num",   False),
    152: ("Date de valeur",                  8,  "Date",  False),
    160: ("Date 1 libre",                    8,  "Date",  False),
    168: ("Date 2 libre",                    8,  "Date",  False),
    176: ("Libelle compte",                 30,  "Alpha", False),
    206: ("Flag modification mouvement",     1,  "Num",   False),
    207: ("Numero ligne modele saisie",     11,  "Num",   False),
    218: ("Qualifiant mouvement",            2,  "Alpha", False),
    220: ("Taux de TVA",                     5,  "Num",   False),
    225: ("Code devise",                     3,  "Alpha", False),
    228: ("Montant debit devise",           11,  "Num",   False),
    239: ("Montant credit devise",          11,  "Num",   False),
    250: ("Taux de change",                  8,  "Num",   False),
    258: ("Filer",                           5,  "Num",   False),
    263: ("Filer",                           5,  "Num",   False),
    268: ("Filer",                           5,  "Num",   False),
    273: ("Filer",                           2,  "Alpha", False),
    275: ("Filer",                           8,  "Date",  False),
    283: ("Filer",                           3,  "Alpha", False),
    286: ("Filer",                           1,  "Num",   False),
}

STRUCT_TVA = {
    1:   ("Type enregistrement",             6,  "Alpha", True),
    7:   ("Code TVA",                        2,  "Alpha", True),
    9:   ("Libelle du code TVA",            30,  "Alpha", True),
    39:  ("Compte de TVA",                  10,  "Alpha", True),
    49:  ("Taux",                            5,  "Num",   True),
    54:  ("Type TVA",                        2,  "Alpha", False),
    56:  ("Flag de positionnement",          2,  "Alpha", False),
    58:  ("Code emplacement liasse",         5,  "Alpha", False),
    63:  ("TVA sur encaissement",            1,  "Num",   False),
    64:  ("TVA 0",                           1,  "Num",   False),
    65:  ("Taux deduction",                  6,  "Num",   False),
    71:  ("Classe de TVA",                   2,  "Alpha", False),
    73:  ("Flag TVA encaissement compta",    1,  "Num",   False),
    74:  ("Code type d'operation",          10,  "Alpha", False),
    84:  ("Code type de taux",              10,  "Alpha", False),
    94:  ("Date debut validite",             8,  "Date",  False),
    102: ("Date fin validite",               8,  "Date",  False),
    110: ("Code TVA autoliquidation",        2,  "Alpha", False),
    112: ("Prorata",                         1,  "Num",   False),
    113: ("Code TVA d'equivalence",          2,  "Alpha", False),
}

STRUCT_JOU = {
    1:  ("Type enregistrement",              6,  "Alpha", True),
    7:  ("Code journal",                     2,  "Alpha", True),
    9:  ("Libelle du journal",              30,  "Alpha", True),
    39: ("Type du journal",                  2,  "Alpha", False),
    41: ("Classe du journal",                2,  "Alpha", False),
    43: ("Type d'extourne",                  2,  "Alpha", False),
    45: ("Compte de contre partie",         10,  "Alpha", False),
    55: ("Filler",                           8,  "Num",   False),
    63: ("Filler",                           8,  "Num",   False),
    71: ("Filler",                           8,  "Num",   False),
    79: ("Filler",                           2,  "Num",   False),
    81: ("Flag incrementation n piece",      1,  "Num",   False),
    82: ("Flag arret numero de piece",       1,  "Num",   False),
    83: ("Flag arret date de facture",       1,  "Num",   False),
    84: ("Flag journal mensuel",             1,  "Num",   False),
    85: ("Flag accepte date d'echeance",     1,  "Num",   False),
}

STRUCT_ECHMVT = {
    1:  ("Type enregistrement",              6,  "Alpha", True),
    7:  ("Montant TTC",                     13,  "Num",   True),
    20: ("Taux TTC",                        10,  "Num",   False),
    30: ("Date d'echeance",                  8,  "Date",  True),
    38: ("Type de reglement",                2,  "Alpha", False),
    40: ("Echeance bloquee",                 1,  "Num",   False),
    41: ("Echeance reglee",                  1,  "Num",   False),
    42: ("Montant en devise",               13,  "Num",   False),
    55: ("Mode de reglement",               10,  "Alpha", False),
    65: ("Compte de reglement",             12,  "Alpha", False),
    77: ("Numero de reglement",              8,  "Alpha", False),
    85: ("Montant regle",                   13,  "Num",   False),
}

STRUCT_ANAMVT = {
    1:  ("Type enregistrement",              6,  "Alpha", True),
    7:  ("Code de l'activite",               6,  "Alpha", True),
    13: ("Code de la decoupe",               2,  "Alpha", False),
    15: ("Libelle",                         40,  "Alpha", False),
    55: ("Pourcentage",                     10,  "Num",   False),
    65: ("Prorata",                          1,  "Num",   False),
}

STRUCT_TIERS = {
    1:   ("Type enregistrement",             6,  "Alpha", True),
    7:   ("Identifiant 1",                  30,  "Alpha", True),
    37:  ("Identifiant 2",                  30,  "Alpha", False),
    67:  ("Adresse 1",                      30,  "Alpha", False),
    97:  ("Adresse 2",                      30,  "Alpha", False),
    127: ("Pays",                            5,  "Alpha", False),
    132: ("Code postal",                     8,  "Alpha", False),
    140: ("Commune",                        30,  "Alpha", False),
    170: ("Telephone",                      17,  "Alpha", False),
    187: ("Fax",                            17,  "Alpha", False),
    204: ("Numero de TVA",                  14,  "Alpha", False),
    218: ("Numero d'identite fiscale",      10,  "Alpha", False),
    228: ("Guichet",                         5,  "Alpha", False),
    233: ("Etablissement",                   5,  "Alpha", False),
    238: ("Numero de compte bancaire",      20,  "Alpha", False),
    258: ("Releve d'identite bancaire",      2,  "Alpha", False),
    260: ("Zone libre",                     30,  "Alpha", False),
    290: ("Zone libre Num",                 15,  "Num",   False),
    305: ("Zone libre Date",                 8,  "Date",  False),
    313: ("Telephone 2",                    17,  "Alpha", False),
    330: ("Indicateur presence Email",       1,  "Num",   False),
    331: ("Indicateur presence Web",         1,  "Num",   False),
    332: ("Domiciliation",                  30,  "Alpha", False),
    362: ("Siret",                          20,  "Alpha", False),
    382: ("Region",                         30,  "Alpha", False),
    412: ("Adresse 3",                      30,  "Alpha", False),
    442: ("Interlocuteur - Nom",            30,  "Alpha", False),
    472: ("Representant",                    7,  "Alpha", False),
    479: ("Secteur",                         7,  "Alpha", False),
    486: ("Code BIC",                       11,  "Alpha", False),
    497: ("IBAN",                           34,  "Alpha", False),
    531: ("Titulaire du compte",            80,  "Alpha", False),
    611: ("Code du tiers",                  10,  "Alpha", False),
    621: ("Role du tiers",                   2,  "Alpha", False),
    623: ("Nature du tiers",                 2,  "Alpha", False),
    625: ("Code INSEE forme juridique",      6,  "Alpha", False),
    631: ("Interlocuteur - Prenom",         30,  "Alpha", False),
    661: ("Nom commercial",                 80,  "Alpha", False),
}

STRUCTURES = {
    "VER":    STRUCT_VER,
    "DOS":    STRUCT_DOS,
    "EXO":    STRUCT_EXO,
    "CPT":    STRUCT_CPT,
    "ECR":    STRUCT_ECR,
    "MVT":    STRUCT_MVT,
    "TVA":    STRUCT_TVA,
    "JOU":    STRUCT_JOU,
    "ECHMVT": STRUCT_ECHMVT,
    "ANAMVT": STRUCT_ANAMVT,
    "TIERS":  STRUCT_TIERS,
}
